#!/bin/bash

echo "Installing Ansible"

sudo apt-get install -y software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

echo "Installing git and cloning the repo"
sudo apt-get install -y git
git clone https://github.com/thecoshman/zipper.git

echo "Running bootstrap playbook"
cd zipper
echo "Well... once it's wrote..."

echo "Self deleting to be nice and clean, you should never need to run this again"
rm -- "$0"
