---

- name: Update cache and pacakges to latest
  apt:
    update_cache: yes
    upgrade: safe

- name: Perform distribution upgrade
  apt:
    update_cache: yes
    upgrade: dist
  when: distribution_upgrade

- name: Install common packages
  apt: name={{item}} state=latest
  with_items:
    - htop
    - lnav
    - git
    - vim

- name: Copy configs
  template:
    src: "../templates/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '.vimrc', dest: '~/.vimrc' }
    
