---

- name: Add repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
    state: present

- name: Add repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install
  apt:
    update_cache: yes
    name: "spotify-client"
    state: latest

