---

- name: Make folder to download Dropbox
  file:
    name: /tmp/dropbox
    state: directory

- name: Get Dropbox package
  get_url:
    url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
    dest: /tmp/dropbox/db.deb

- name: Install Dropbox
  apt:
    deb: /tmp/dropbox/db.deb
