---

- name: Install
  apt:
    name: git
    state: latest

- name: Configure 
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: 'user.email', value: 'thecoshman@gmail.com' }
    - { name: 'user.name', value: 'thecoshman' }
    - { name: 'push.default', value: 'simple' }
    - { name: 'core.editor', value: 'vi' }

