---

- name: Clean old Docker installations
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io

- name: Install required pacakges for installation
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add repository key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 0EBFCD88
    state: present

- name: Add repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install
  apt:
    update_cache: yes
    name: "docker-ce"
    state: latest

- name: Docker group for non sudo invocation
  group:
    name: docker
    state: present

# This step requires a reboot to take effect
- name: User in 'docker' group
  user:
    name: thecoshman
    append: yes
    groups: docker
  
